//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP02._01Proga
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonements1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Abonements1()
        {
            this.Clients = new HashSet<Clients1>();
        }
    
        public int ID_Abonement { get; set; }
        public decimal Cost { get; set; }
        public int ColvoPosesheniy { get; set; }
        public int TypeDeystviya_ID { get; set; }
        public int SrokAbonementa_ID { get; set; }
    
        public virtual SrokiAbonements SrokiAbonements { get; set; }
        public virtual TypeDeystviyas1 TypeDeystviyas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clients1> Clients { get; set; }
    }
}
