//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP02._01Proga
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Treners()
        {
            this.Zaniatiya = new HashSet<Zaniatiya>();
        }
    
        public int ID_Trener { get; set; }
        public string TrenerName { get; set; }
        public string TrenerSurname { get; set; }
        public string TrenerMiddleName { get; set; }
        public string Passwordd { get; set; }
        public string Email { get; set; }
        public int TrenerTypes_ID { get; set; }
    
        public virtual TrenerTypes TrenerTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zaniatiya> Zaniatiya { get; set; }
    }
}
