//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP02._01Proga
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zaniatiya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zaniatiya()
        {
            this.ZaniatiyaClients = new HashSet<ZaniatiyaClients>();
        }
    
        public int ID_Zaniatiya { get; set; }
        public string NameZaniatiya { get; set; }
        public string DateZaniatiya { get; set; }
        public int ColvoHours { get; set; }
        public int ColvoUchastnikov { get; set; }
        public int Trener_ID { get; set; }
    
        public virtual Treners Treners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZaniatiyaClients> ZaniatiyaClients { get; set; }
    }
}
