//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP02._01Proga
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZaniatiyaClients
    {
        public int ID_ZaniatiyaClients { get; set; }
        public int Zaniatiya_ID { get; set; }
        public int Client_ID { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Zaniatiya Zaniatiya { get; set; }
    }
}
